"""Provider-agnostic OAuth contract. SocialAccountManager never sees endpoints."""

from __future__ import annotations

from typing import Any, Protocol

from social.auth.credentials import CredentialRecord
from social.auth.oauth import OAuthStart, RevokeResult


class OAuthAdapter(Protocol):
    def authorization_url(self, *, state: str | None = None, redirect_uri: str | None = None) -> OAuthStart: ...
    def exchange_code(self, code: str, *, code_verifier: str = "", redirect_uri: str | None = None) -> CredentialRecord: ...
    def refresh(self, refresh_token: str) -> CredentialRecord: ...
    def revoke(self, token: str, *, token_type_hint: str = "access_token") -> RevokeResult: ...
    def validate(self, access_token: str) -> dict[str, Any]: ...
    def scopes(self) -> str: ...
