"""Unique SocialProvider contract. Agents never call this directly."""

from __future__ import annotations

from typing import Any, Protocol

from integrations.contracts.distribution import DistributionJob, MediaUploadResult, ProviderHealth, Publication
from social.accounts.models import SocialAccount, SocialProviderCapabilities


class SocialProvider(Protocol):
    provider: str

    def health(self) -> ProviderHealth: ...
    def authenticate(self, authorization: dict[str, Any] | None = None) -> bool: ...
    def list_accounts(self) -> list[SocialAccount]: ...
    def get_account(self, account_id: str) -> SocialAccount: ...
    def capabilities(self, account_id: str) -> SocialProviderCapabilities: ...
    def publish(self, job: DistributionJob) -> dict[str, Any]: ...
    def schedule(self, job: DistributionJob) -> dict[str, Any]: ...
    def get_status(self, provider_post_id: str, *, account_id: str = "", provider_object_type: str = "") -> dict[str, Any]: ...
    def delete(self, provider_post_id: str) -> dict[str, Any]: ...
    def analytics(self, publication: Publication) -> dict[str, Any | None]: ...
    def upload_media(self, source_path: str) -> MediaUploadResult: ...
